### ISSUE TITLE
empty repository

### ISSUE THREAD

**Issue by ArtGangsta** [HaileyBot/haileybot#1]
is this repository meant to be empty?

**Comment by cheesits456** [comment]
o god i completely forgot about this repo - the plan was to upload the source code for some of the commands my bot has, some of the custom functions and classes ive written, etc, with extensive comments added in so people can potentially learn from it. But I kept putting off adding in the comments and stuff so many times that, evidently, i forgot about it entirely. big oof.
![oof](https://user-images.githubusercontent.com/35486894/89158172-909c7b00-d522-11ea-8de7-5630f4dc83dc.jpg)

**Comment by Fat-Yeetus** [comment]
> o god i completely forgot about this repo - the plan was to upload the source code for some of the commands my bot has, some of the custom functions and classes ive written, etc, with extensive comments added in so people can potentially learn from it. But I kept putting off adding in the comments and stuff so many times that, evidently, i forgot about it entirely. big oof.
> ![oof](https://user-images.githubusercontent.com/35486894/89158172-909c7b00-d522-11ea-8de7-5630f4dc83dc.jpg)

Why would you even want to do that in the first place lol

**Comment by Fat-Yeetus** [comment]
Sounds like a terrible idea tbh

**Comment by cheesits456** [comment]
> the plan was to upload the source code for ***some*** of the commands my bot has, ***some*** of the custom functions and classes ive written, etc, with extensive comments added in ***so people can potentially learn from it***.

in what way is that a "terrible idea"?
